services:
  nodeapp:
    depends_on:
      - redis
    networks:
      - network
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - network
networks:
    network:
  