services:
  nodeapp-dapr:
    image: daprio/daprd:latest
    depends_on:
      - nodeapp-nodeapp
      - dapr-placement
    command: ["./daprd",
      "-app-id", "nodeapp",
      "-app-port", "3000",
      "-components-path", "/components"
      ]
    volumes:
      - "../components/:/components"
  