apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: dapr-workload
entity:
  name: dapr-workload
  type: workload
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        outputs: |
          update:
            - op: add
              path: /spec/annotations
              value:
                dapr.io/enabled: "true"
                dapr.io/app-id: {{ .resource.id | quote }}
                {{- if .resource.spec.service }}
                {{- $port := values .resource.spec.service.ports | first }}
                dapr.io/app-port: {{ $port.container_port | quote }}
                {{- end}}
                dapr.io/enable-api-logging: "true"
  criteria:
    - {}