services:
  nodeapp:
    depends_on:
      - redis
    networks:
      - network
  nodeapp-dapr:
    image: daprio/daprd:latest
    depends_on:
      - nodeapp
      - dapr-placement
    command: ["./daprd",
      "-app-id", "nodeapp",
      "-app-port", "3000",
      "-components-path", "/components"
      ]
    volumes:
      - "./components/:/components"
    network_mode: "service:nodeapp"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - network
  pythonapp:
    depends_on:
      - nodeapp
    networks:
      - network
  pythonapp-dapr:
    image: daprio/daprd:latest
    depends_on:
      - pythonapp
    command: ["./daprd",
      "-app-id", "pythonapp"
      ]
    network_mode: "service:pythonapp"
  dapr-placement:
    image: daprio/dapr:latest
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - network
networks:
    network:
  