name: cd-apps
permissions:
  contents: read
  id-token: write
on:
  push:
    branches:
      - main
env:
  ENVIRONMENT_ID: development
  SCORE_HUMANITEC_VERSION: 'latest'
  APP_NAME: dapr-helloworld
  HUMCTL_VERSION: '0.11.0'
jobs:
  deploy-humanitec:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install humctl
        uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: create humanitec app
        run: |
          humctl create app ${{ env.APP_NAME }} \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ secrets.HUMANITEC_ORG }} \
              --name ${{ env.APP_NAME }} \
              || true
      - name: install score-humanitec
        uses: score-spec/setup-score@v2
        with:
          file: score-humanitec
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SCORE_HUMANITEC_VERSION }}
      - name: deploy score-humanitec - node
        run: |
          score-humanitec delta \
              --retry \
              --deploy \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ secrets.HUMANITEC_ORG }} \
              --app ${{ env.APP_NAME }} \
              --env ${{ env.ENVIRONMENT_ID }} \
              -f apps/hello-world-k8s/node/score.yaml
      - name: deploy score-humanitec - python
        run: |
          score-humanitec delta \
              --retry \
              --deploy \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ secrets.HUMANITEC_ORG }} \
              --app ${{ env.APP_NAME }} \
              --env ${{ env.ENVIRONMENT_ID }} \
              -f apps/hello-world-k8s/python/score.yaml