name: cd-apps
permissions:
  contents: read
  id-token: write
on:
  push:
    branches:
      - main
env:
  ENVIRONMENT_ID: development
  APP_NAME: dapr-helloworld
  HUMCTL_VERSION: '0.23.2'
jobs:
  deploy-humanitec:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install humctl
        uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: create app
        run: |
          humctl create app ${{ env.APP_NAME }} \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ secrets.HUMANITEC_ORG }} \
              --name ${{ env.APP_NAME }} \
              || true
      - name: deploy workloads
        run: |
          humctl score deploy \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ secrets.HUMANITEC_ORG }} \
              --app ${{ env.APP_NAME }} \
              --env ${{ env.ENVIRONMENT_ID }} \
              -f apps/hello-world/score.deploy.yaml
    