name: cd-resources
permissions:
  contents: read
  id-token: write
on:
  push:
    branches:
      - main
env:
  HUMCTL_VERSION: '0.25.0'
jobs:
  deploy-humanitec:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        resources: ["dapr-workload", "in-cluster-redis", "redis-dapr-state"]
    steps:
      - uses: actions/checkout@v4
      - name: install humctl
        uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: apply humanitec resources
        run: |
          humctl apply \
              -f humanitec-resources/${{ matrix.resources }}.yaml \
              --org ${{ secrets.HUMANITEC_ORG }} \
              --token ${{ secrets.HUMANITEC_TOKEN }}