name: ci
permissions:
  contents: read
on:
  push:
jobs:
  job:
    strategy:
      matrix:
        apps: ["hello-world/node", "hello-world/python", "pizza/delivery", "pizza/kitchen", "pizza/store"]
    runs-on: ubuntu-22.04
    env:
      HUMCTL_VERSION: '0.23.2'
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install humctl
        uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: humctl score validate
        run: |
          humctl score validate \
              apps/${{ matrix.apps }}/score.yaml \
              --local