name: ci
permissions:
  contents: read
on:
  push:
jobs:
  score-validate:
    runs-on: ubuntu-22.04
    env:
      HUMCTL_VERSION: '0.25.0'
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install humctl
        uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: humctl score validate node
        run: |
          humctl score validate \
              score-node.yaml \
              --local
      - name: humctl score validate python
        run: |
          humctl score validate \
              score-python.yaml \
              --local
  score-compose:
    runs-on: ubuntu-22.04
    env:
      HUMCTL_VERSION: '0.25.0'
      SCORE_COMPOSE_VERSION: 'latest'
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install score-compose
        uses: score-spec/setup-score@v3
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SCORE_COMPOSE_VERSION }}
      - name: make compose-test
        run: |
          make compose-test
  score-k8s:
    runs-on: ubuntu-22.04
    env:
      HUMCTL_VERSION: '0.25.0'
      SCORE_K8S_VERSION: 'latest'
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install score-k8s
        uses: score-spec/setup-score@v3
        with:
          file: score-k8s
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SCORE_K8S_VERSION }}
      - name: make kind-create-cluster
        run: |
          make kind-create-cluster
      - name: make k8s-up
        id: k8s-up
        run: |
          make k8s-up
      - name: catch k8s-up errors
        if: ${{ failure() && steps.k8s-up.outcome == 'failure' }}
        run: |
          kubectl get events
          kubectl logs \
              -l app.kubernetes.io/name=nodeapp