name: ci
permissions:
  contents: read
on:
  push:
jobs:
  score-validate:
    strategy:
      matrix:
        apps: ["hello-world/node", "hello-world/python", "pizza/delivery", "pizza/kitchen", "pizza/store"]
    runs-on: ubuntu-22.04
    env:
      HUMCTL_VERSION: '0.25.0'
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install humctl
        uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: humctl score validate
        run: |
          humctl score validate \
              apps/${{ matrix.apps }}/score.yaml \
              --local
  score-compose:
    runs-on: ubuntu-22.04
    env:
      HUMCTL_VERSION: '0.25.0'
      SCORE_COMPOSE_VERSION: 'latest'
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install score-compose
        uses: score-spec/setup-score@v3
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SCORE_COMPOSE_VERSION }}
      - name: make compose-test
        run: |
          cd apps/hello-world/node
          make compose-test