name: ci
permissions:
  contents: read
on:
  push:
jobs:
  job:
    strategy:
      matrix:
        apps: ["hello-world-k8s/node", "hello-world-k8s/python", "pizza/store"]
    runs-on: ubuntu-22.04
    env:
      SCORE_HUMANITEC_VERSION: 'latest'
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install score-humanitec
        uses: score-spec/setup-score@v2
        with:
          file: score-humanitec
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SCORE_HUMANITEC_VERSION }}
      - name: score-humanitec run
        run: |
          score-humanitec run \
              --env development \
              -f apps/${{ matrix.apps }}/score.yaml